apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: prytaneum-backendconfig
  namespace: production
spec:
  timeoutSec: 1800
  connectionDraining:
    drainingTimeoutSec: 1800
  