export const QUESTIONS_MAX_LENGTH = 500;
export const FEEDBACK_MAX_LENGTH = 500;
export const FEEDBACK_PROMPT_MAX_LENGTH = 500;
export const FEEDBACK_PROMPT_RESPONSE_MAX_LENGTH = 500;
export const BROADCAST_MESSAGE_MAX_LENGTH = 500;
export const CHOICE_MAX_LENGTH = 250;
export const CHOICES_MAX_AMOUNT = 20;
export const STARTING_CHOICE_AMOUNT = 4;
