packageExtensions:
  "@endemolshinegroup/cosmiconfig-typescript-loader@*":
    peerDependenciesMeta:
      typescript:
        optional: true
  "@mdx-js/loader@*":
    dependencies:
      react: "*"
  "@storybook/core@*":
    dependencies:
      webpack: "*"
  "@types/react-relay@^13.0.1":
    peerDependencies:
      "@types/relay-runtime": ^13.0.1
  babel-plugin-relay@*:
    dependencies:
      "@babel/runtime": "*"
  eslint-config-airbnb-typescript@*:
    dependencies:
      "@babel/core": "*"
      eslint: "*"
      eslint-plugin-import: "*"
  eslint-config-react-app@*:
    dependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
    peerDependencies:
      "@typescript-eslint/eslint-plugin": "*"
  fastify-cookie@*:
    peerDependencies:
      fastify: "*"
  mercurius@*:
    peerDependencies:
      fastify: "*"
  pino@*:
    dependencies:
      pino-pretty: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
