logFilters:
    - code: YN0062
      level: discard

packageExtensions:
    '@endemolshinegroup/cosmiconfig-typescript-loader@*':
        peerDependenciesMeta:
            typescript:
                optional: true
    '@mdx-js/loader@*':
        dependencies:
            react: '*'
    '@storybook/core@*':
        dependencies:
            webpack: '*'
    babel-plugin-relay@*:
        dependencies:
            '@babel/runtime': '*'
    eslint-config-airbnb-typescript@*:
        dependencies:
            '@babel/core': '*'
            eslint: '*'
            eslint-plugin-import: '*'
    eslint-config-react-app@*:
        dependencies:
            '@babel/plugin-syntax-flow': '*'
            '@babel/plugin-transform-react-jsx': '*'
        peerDependencies:
            '@typescript-eslint/eslint-plugin': '*'
    fastify-cookie@*:
        peerDependencies:
            fastify: '*'
    mercurius@*:
        peerDependencies:
            fastify: '*'
    pino@*:
        dependencies:
            pino-pretty: '*'

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
      spec: '@yarnpkg/plugin-workspace-tools'
    - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
      spec: '@yarnpkg/plugin-typescript'
    - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
      spec: '@yarnpkg/plugin-version'

yarnPath: .yarn/releases/yarn-3.1.1.cjs
