logFilters:
    - code: YN0062
      level: discard

packageExtensions:
    '@endemolshinegroup/cosmiconfig-typescript-loader@*':
        peerDependenciesMeta:
            typescript:
                optional: true
    '@mdx-js/loader@*':
        dependencies:
            react: '*'
    '@storybook/core@*':
        dependencies:
            webpack: '*'
    babel-plugin-relay@*:
        dependencies:
            '@babel/runtime': '*'
    eslint-config-airbnb-typescript@*:
        dependencies:
            eslint: '*'
            eslint-plugin-import: '*'
            eslint-plugin-jsx-a11y: '*'
            eslint-plugin-react: '*'
            eslint-plugin-react-hooks: '*'
    fastify-cookie@*:
        peerDependencies:
            fastify: '*'
    mercurius@*:
        peerDependencies:
            fastify: '*'
    pino@*:
        dependencies:
            pino-pretty: '*'
    react-dev-utils@*:
        dependencies:
            typescript: '*'
            webpack: '*'
    relay-compiler@11.0.2:
        peerDependencies:
            '@types/react-relay': '*'
            '@types/relay-runtime': '*'
            relay-compiler-language-typescript: v14.0.0
            typescript: '*'

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
      spec: '@yarnpkg/plugin-workspace-tools'
    - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
      spec: '@yarnpkg/plugin-typescript'
    - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
      spec: '@yarnpkg/plugin-version'

yarnPath: .yarn/releases/yarn-3.0.1.cjs
