packageExtensions:
    '@mdx-js/loader@*':
        dependencies:
            react: '*'
    '@storybook/core@*':
        dependencies:
            webpack: '*'
    '@types/react-relay@^13.0.1':
        peerDependencies:
            '@types/relay-runtime': ^13.0.1
    '@graphql-codegen/cli@*':
        peerDependencies:
            '@types/node': '*'
            'ts-node': '*'
            'typescript': '*'
            '@babel/core': '*'
    '@graphql-tools/graphql-tag-pluck@*':
        peerDependencies:
            '@babel/core': '*'
    '@graphql-tools/code-file-loader@*':
        peerDependencies:
            '@babel/core': '*'
    '@graphql-tools/git-loader@*':
        peerDependencies:
            '@babel/core': '*'
    '@graphql-tools/github-loader@*':
        peerDependencies:
            '@babel/core': '*'
    graphql-config@*:
        peerDependencies:
            '@types/node': '*'
            'typescript': '*'
    babel-plugin-relay@*:
        dependencies:
            '@babel/runtime': '*'
    eslint-config-airbnb-typescript@*:
        dependencies:
            '@babel/core': '*'
            eslint: '*'
            eslint-plugin-import: '*'
    eslint-config-react-app@*:
        dependencies:
            '@babel/plugin-syntax-flow': '*'
            '@babel/plugin-transform-react-jsx': '*'
        peerDependencies:
            '@typescript-eslint/eslint-plugin': '*'
    eslint-config-next@13.4.18:
        dependencies:
            next: '13.4.18'
            react: '^18.2.0'
            react-dom: '^18.2.0'
    notistack@*:
        dependencies:
            csstype: '*'
    mercurius@*:
        peerDependencies:
            fastify: '*'
    pino@*:
        dependencies:
            pino-pretty: '*'
    ts-node-dev@*:
        peerDependencies:
            '@types/node': '*'

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
      spec: '@yarnpkg/plugin-workspace-tools'
    - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
      spec: '@yarnpkg/plugin-typescript'
    - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
      spec: '@yarnpkg/plugin-version'
    - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
      spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.2.3.cjs
