version: '3.6'
services:
    app:
        user: '${UID}:${GID}'
        container_name: app
        build: .
        tty: true
        volumes:
            - type: bind
              source: .
              target: /usr/monorepo
        working_dir: /usr/monorepo
        ports:
            - 8080:8080
        environment:
            - NODE_ENV=development
            - DATABASE_URL=postgresql://postgres:postgrespassword@db:5432
    db:
        container_name: db
        user: postgres
        image: postgres:13
        restart: always
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgrespassword
            POSTGRES_DB: postgres

volumes:
    db_data:
