version: '3.6'
services:
    cc2c-app:
        user: '${UID}:${GID}'
        container_name: cc2c-app
        build:
            context: .
            dockerfile: ./app/cc2c/Dockerfile
        tty: true
        volumes:
            - type: bind
              source: .
              target: /usr/monorepo
        working_dir: /usr/monorepo
        ports:
            - 3000:3000
        environment:
            NODE_ENV: development
            DATABASE_URL: postgresql://postgres:postgrespassword@cc2c-db:5432
        depends_on:
            - cc2c-db
        links:
            - cc2c-db
    cc2c-db:
        container_name: cc2c-db
        user: postgres
        image: postgres:13
        restart: always
        volumes:
            - cc2c_db_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgrespassword
            POSTGRES_DB: postgres
    prisma-studio:
        container_name: prisma-studio
        image: timothyjmiller/prisma-studio:latest
        restart: unless-stopped
        environment:
            PROJECT_NAME: cc2c
            POSTGRES_DATABASE: postgres
            POSTGRES_HOST: cc2c-db
            POSTGRES_USERNAME: postgres
            POSTGRES_PASSWORD: postgrespassword
            POSTGRES_PORT: 5432
            PRISMA_STUDIO_PORT: 5555
            POSTGRES_PATH: cc2c_db_data
            POSTGRES_URL: postgresql://postgres:postgrespassword@cc2c-db:5432
        ports:
            - 5555:5555
        depends_on:
            - cc2c-db

volumes:
    cc2c_db_data:
