apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
    name: gcp-backendconfig
    namespace: cc2c-development
spec:
    timeoutSec: 1800
    connectionDraining:
        drainingTimeoutSec: 1800
