apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./prytaneum-client-deployment.yml
  - ./prytaneum-client-service.yml
  - ./prytaneum-client-configmap.yml
  - ./prytaneum-frontend-config.yml
