apiVersion: v1
kind: ConfigMap
metadata:
  name: prytaneum-server-config
  namespace: production
  labels:
    app: prytaneum-server
data:
  HOST: 0.0.0.0
  NODE_ENV: production
  SERVER_PORT: "3002"
