apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: cc2c
    name: cc2c
    namespace: cc2c-development
spec:
    selector:
        matchLabels:
            app: cc2c
    replicas: 4
    revisionHistoryLimit: 100
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 50%
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: cc2c
        spec:
            volumes:
                - name: google-cloud-key
                  secret:
                      secretName: gcp-storage-credentials
            containers:
                - name: cc2c
                  image: gcr.io/PROJECT_ID/CC2C_IMAGE:TAG
                  volumeMounts:
                      - name: google-cloud-key
                        mountPath: /var/secrets/google
                  imagePullPolicy: IfNotPresent
                  resources:
                      limits:
                          cpu: 250m
                          memory: 500Mi
                      requests:
                          cpu: 150m
                          memory: 300Mi
                  env:
                      - name: GOOGLE_APPLICATION_CREDENTIALS
                        value: /var/secrets/google/key.json
                      - name: NODE_ENV
                        valueFrom:
                            configMapKeyRef:
                                key: NODE_ENV
                                name: cc2c-config
                      - name: ORIGIN_URL
                        valueFrom:
                            configMapKeyRef:
                                key: ORIGIN_URL
                                name: cc2c-config
                      - name: HOST
                        valueFrom:
                            configMapKeyRef:
                                key: HOST
                                name: cc2c-config
                      - name: PORT
                        valueFrom:
                            configMapKeyRef:
                                key: PORT
                                name: cc2c-config
                      - name: POD_ID
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
                      - name: GCP_PROJECT_ID
                        valueFrom:
                            configMapKeyRef:
                                key: GCP_PROJECT_ID
                                name: cc2c-config
                      - name: GCP_SERVICE_URL
                        valueFrom:
                            configMapKeyRef:
                                key: GCP_SERVICE_URL
                                name: cc2c-config
                      - name: NEXTAUTH_URL
                        valueFrom:
                            configMapKeyRef:
                                key: NEXTAUTH_URL
                                name: cc2c-config
                      - name: DATABASE_URL
                        valueFrom:
                            secretKeyRef:
                                key: database_url
                                name: db-secret
                      - name: MAILGUN_API_KEY
                        valueFrom:
                            secretKeyRef:
                                key: api_key
                                name: mailgun-secret
                      - name: MAILGUN_DOMAIN
                        valueFrom:
                            secretKeyRef:
                                key: domain
                                name: mailgun-secret
                      - name: MAILGUN_FROM_EMAIL
                        valueFrom:
                            secretKeyRef:
                                key: from_email
                                name: mailgun-secret
