import type { Round1Persona } from './round1Covariates';

/** The first 20 complete demographic rows from FGDT's twin_personalities_file.csv. */
export const ROUND1_PERSONAS: readonly Round1Persona[] = [
    {
        region: 'South',
        gender: 'Male',
        age: '18-29',
        education: 'Some college, no degree',
        race: 'White',
        uscitizen: 'Yes',
        maritalstatus: 'Never been married',
        religion: 'Protestant',
        religionattend: 'Once or twice a month',
        partyid: 'Republican',
        income: '$100,000 or more',
        politics: 'Conservative',
        hhsize: '4',
        employstatus: 'Student',
    },
    {
        region: 'Midwest',
        gender: 'Female',
        age: '50-64',
        education: 'College graduate/some postgrad',
        race: 'White',
        uscitizen: 'Yes',
        maritalstatus: 'Married',
        religion: 'Nothing in particular',
        religionattend: 'Seldom',
        partyid: 'Democrat',
        income: '$100,000 or more',
        politics: 'Liberal',
        hhsize: '2',
        employstatus: 'Unemployed',
    },
    {
        region: 'South',
        gender: 'Female',
        age: '50-64',
        education: 'Postgraduate',
        race: 'White',
        uscitizen: 'Yes',
        maritalstatus: 'Married',
        religion: 'Protestant',
        religionattend: 'Once or twice a month',
        partyid: 'Republican',
        income: '$50,000-$75,000',
        politics: 'Conservative',
        hhsize: '3',
        employstatus: 'Full-time employment',
    },
    {
        region: 'West',
        gender: 'Female',
        age: '30-49',
        education: 'Associate\'s degree',
        race: 'White',
        uscitizen: 'Yes',
        maritalstatus: 'Separated',
        religion: 'Other',
        religionattend: 'Never',
        partyid: 'Independent',
        income: '$50,000-$75,000',
        politics: 'Liberal',
        hhsize: '4',
        employstatus: 'Self-employed',
    },
    {
        region: 'Midwest',
        gender: 'Female',
        age: '50-64',
        education: 'High school graduate',
        race: 'Black',
        uscitizen: 'Yes',
        maritalstatus: 'Never been married',
        religion: 'Other',
        religionattend: 'Seldom',
        partyid: 'Republican',
        income: '$50,000-$75,000',
        politics: 'Conservative',
        hhsize: '2',
        employstatus: 'Full-time employment',
    },
    {
        region: 'South',
        gender: 'Male',
        age: '18-29',
        education: 'College graduate/some postgrad',
        race: 'Asian',
        uscitizen: 'Yes',
        maritalstatus: 'Never been married',
        religion: 'Nothing in particular',
        religionattend: 'Never',
        partyid: 'Democrat',
        income: '$75,000-$100,000',
        politics: 'Liberal',
        hhsize: '1',
        employstatus: 'Full-time employment',
    },
    {
        region: 'West',
        gender: 'Male',
        age: '18-29',
        education: 'Some college, no degree',
        race: 'Hispanic',
        uscitizen: 'Yes',
        maritalstatus: 'Never been married',
        religion: 'Buddhist',
        religionattend: 'Never',
        partyid: 'Independent',
        income: 'Less than $30,000',
        politics: 'Moderate',
        hhsize: '1',
        employstatus: 'Student',
    },
    {
        region: 'Midwest',
        gender: 'Female',
        age: '30-49',
        education: 'College graduate/some postgrad',
        race: 'Other',
        uscitizen: 'Yes',
        maritalstatus: 'Never been married',
        religion: 'Nothing in particular',
        religionattend: 'Never',
        partyid: 'Independent',
        income: 'Less than $30,000',
        politics: 'Very liberal',
        hhsize: '1',
        employstatus: 'Full-time employment',
    },
    {
        region: 'South',
        gender: 'Female',
        age: '30-49',
        education: 'Some college, no degree',
        race: 'White',
        uscitizen: 'Yes',
        maritalstatus: 'Never been married',
        religion: 'Protestant',
        religionattend: 'Seldom',
        partyid: 'Independent',
        income: 'Less than $30,000',
        politics: 'Moderate',
        hhsize: '1',
        employstatus: 'Part-time employment',
    },
    {
        region: 'South',
        gender: 'Male',
        age: '50-64',
        education: 'College graduate/some postgrad',
        race: 'Other',
        uscitizen: 'Yes',
        maritalstatus: 'Separated',
        religion: 'Other',
        religionattend: 'Once or twice a month',
        partyid: 'Independent',
        income: '$50,000-$75,000',
        politics: 'Moderate',
        hhsize: 'More than 4',
        employstatus: 'Self-employed',
    },
    {
        region: 'South',
        gender: 'Male',
        age: '18-29',
        education: 'College graduate/some postgrad',
        race: 'Black',
        uscitizen: 'Yes',
        maritalstatus: 'Never been married',
        religion: 'Agnostic',
        religionattend: 'Never',
        partyid: 'Democrat',
        income: 'Less than $30,000',
        politics: 'Liberal',
        hhsize: '1',
        employstatus: 'Self-employed',
    },
    {
        region: 'West',
        gender: 'Male',
        age: '30-49',
        education: 'Some college, no degree',
        race: 'White',
        uscitizen: 'Yes',
        maritalstatus: 'Married',
        religion: 'Nothing in particular',
        religionattend: 'Never',
        partyid: 'Independent',
        income: '$50,000-$75,000',
        politics: 'Moderate',
        hhsize: 'More than 4',
        employstatus: 'Full-time employment',
    },
    {
        region: 'West',
        gender: 'Male',
        age: '50-64',
        education: 'High school graduate',
        race: 'White',
        uscitizen: 'Yes',
        maritalstatus: 'Married',
        religion: 'Protestant',
        religionattend: 'A few times a year',
        partyid: 'Democrat',
        income: '$50,000-$75,000',
        politics: 'Conservative',
        hhsize: '4',
        employstatus: 'Full-time employment',
    },
    {
        region: 'South',
        gender: 'Male',
        age: '18-29',
        education: 'High school graduate',
        race: 'Hispanic',
        uscitizen: 'Yes',
        maritalstatus: 'Living with a partner',
        religion: 'Agnostic',
        religionattend: 'Never',
        partyid: 'Democrat',
        income: '$100,000 or more',
        politics: 'Liberal',
        hhsize: 'More than 4',
        employstatus: 'Full-time employment',
    },
    {
        region: 'South',
        gender: 'Male',
        age: '65+',
        education: 'Some college, no degree',
        race: 'White',
        uscitizen: 'Yes',
        maritalstatus: 'Married',
        religion: 'Protestant',
        religionattend: 'A few times a year',
        partyid: 'Republican',
        income: '$50,000-$75,000',
        politics: 'Very conservative',
        hhsize: '2',
        employstatus: 'Retired',
    },
    {
        region: 'West',
        gender: 'Female',
        age: '18-29',
        education: 'College graduate/some postgrad',
        race: 'Black',
        uscitizen: 'Yes',
        maritalstatus: 'Living with a partner',
        religion: 'Nothing in particular',
        religionattend: 'A few times a year',
        partyid: 'Independent',
        income: '$30,000-$50,000',
        politics: 'Very liberal',
        hhsize: '2',
        employstatus: 'Part-time employment',
    },
    {
        region: 'West',
        gender: 'Male',
        age: '50-64',
        education: 'Postgraduate',
        race: 'Other',
        uscitizen: 'Yes',
        maritalstatus: 'Married',
        religion: 'Agnostic',
        religionattend: 'Never',
        partyid: 'Democrat',
        income: '$100,000 or more',
        politics: 'Moderate',
        hhsize: '3',
        employstatus: 'Full-time employment',
    },
    {
        region: 'West',
        gender: 'Male',
        age: '18-29',
        education: 'High school graduate',
        race: 'Hispanic',
        uscitizen: 'Yes',
        maritalstatus: 'Never been married',
        religion: 'Roman Catholic',
        religionattend: 'A few times a year',
        partyid: 'Democrat',
        income: '$30,000-$50,000',
        politics: 'Liberal',
        hhsize: '3',
        employstatus: 'Full-time employment',
    },
    {
        region: 'Northeast',
        gender: 'Male',
        age: '65+',
        education: 'Postgraduate',
        race: 'White',
        uscitizen: 'Yes',
        maritalstatus: 'Married',
        religion: 'Jewish',
        religionattend: 'Never',
        partyid: 'Democrat',
        income: '$100,000 or more',
        politics: 'Liberal',
        hhsize: '2',
        employstatus: 'Retired',
    },
    {
        region: 'Northeast',
        gender: 'Female',
        age: '65+',
        education: 'Postgraduate',
        race: 'White',
        uscitizen: 'Yes',
        maritalstatus: 'Widowed',
        religion: 'Roman Catholic',
        religionattend: 'Once a week',
        partyid: 'Republican',
        income: '$50,000-$75,000',
        politics: 'Conservative',
        hhsize: '3',
        employstatus: 'Full-time employment',
    },
];
