# Set the version of docker compose to use
version: '3.6'

# The containers that compose the project
services:
    db:
        image: postgres:13
        restart: always
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - '3003:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgrespassword
            POSTGRES_DB: postgres

    cache:
        image: redis:6.2-alpine
        restart: always
        ports:
            - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning
        volumes:
            - cache:/data
        environment:
            REDIS_HOST: cache
            REDIS_PORT: 6379
            REDIS_PASSWORD:
volumes:
    db_data:
    cache:
