apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
replicas:
  - name: prytaneum-client
    count: 1
resources:
  - ./prytaneum-client-deployment.yml
  - ./prytaneum-client-service.yml
  - ./prytaneum-client-configmap.yml
  - ./prytaneum-frontend-config.yml
