#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Exit on script error
set -e

printf "Checking types...\n"
yarn g:typecheck
printf "No type errors! 🎉🎉🎉\n"

printf "Linting project...\n"
yarn g:lint-project
printf "No lint errors! 🎉🎉🎉\n"
