#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Exit on script error
set -e

printf "Checking types...\n"
yarn workspaces foreach -p run typecheck
printf "No type errors! 🎉🎉🎉\n"

printf "Linting project...\n"
yarn workspaces foreach -p run lint
printf "No lint errors! 🎉🎉🎉\n"

printf "E2E testing...\n"
yarn workspace @app/client run test:e2e:ci
printf "All tests passing! 🎉🎉🎉\n"
