name: CC2C build, lint, and test
on:
    pull_request:
        branches:
            - staging
        paths:
            - 'app/cc2c/**'

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        environment: cc2c-development

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: '16'

            - name: Yarn Install
              run: yarn install

            # Build the CC2C app via docker so we are as close to the real build as possible.
            - name: Docker build cc2c
              run: |-
                  docker build \
                    -f ./docker/Dockerfile.cc2c \
                    --build-arg GITHUB_SHA="$GITHUB_SHA" \
                    --build-arg GITHUB_REF="$GITHUB_REF" \
                    --build-arg DEPLOYMENT_ENV="development" \
                    .
            # Build the gcp service via docker so we are as close to the real build as possible.
            - name: Docker build gcp
              run: |-
                  docker build \
                    -f ./docker/Dockerfile.gcp \
                    --build-arg GITHUB_SHA="$GITHUB_SHA" \
                    --build-arg GITHUB_REF="$GITHUB_REF" \
                    --build-arg DEPLOYMENT_ENV="development" \
                    .

    test:
        name: Test
        runs-on: ubuntu-latest
        environment: cc2c-development

        steps:
            - name: Setup
              uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: '16'

            - name: Yarn Install
              run: yarn install

            - name: Test Project
              run: yarn workspace @app/cc2c test:ci

    lint:
        name: Lint
        runs-on: ubuntu-latest
        environment: cc2c-development

        steps:
            - name: Setup
              uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: '16'

            - name: Yarn Install
              run: yarn install

            - name: Lint Project
              run: yarn workspace @app/cc2c lint
