name: Test deployment for dev docs

on:
    pull_request:
        branches:
            - dev
        paths:
            # Only run when docs are modified
            - 'app/docs/**'

jobs:
    test-deploy:
        name: Test deployment
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  cache: yarn

            - name: Install dependencies
              run: yarn workspace @app/docs install
            - name: Test build website
              run: yarn workspace @app/docs build
